### ISSUE TITLE
UsePlatformDetect not recognized 

### ISSUE THREAD

**Issue by Amine-Smahi** [wieslawsoltes/NXUI#15]
Hello, i created a new console app and added the reference to

`<PackageReference Include="NXUI" Version="11.0.0-preview5" />`

And it seems like UsePlatformDetect is not recognized, what am i missing ?
![image](https://user-images.githubusercontent.com/24621701/216827135-e351b01a-dffe-40b5-93f3-2463b2df30e2.png)

Here is my csproj
`<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia" Version="11.0.0-preview5" />
      <PackageReference Include="NXUI" Version="11.0.0-preview5" />
    </ItemGroup>

</Project>
`

**Comment by wieslawsoltes** [comment]
Add Avalonia.Desktop package reference.
