### ISSUE TITLE
Using more then one file?

### ISSUE THREAD

**Issue by Shadowblitz16** [wieslawsoltes/NXUI#28]
How do I use this in other cs files other then the main toplevel one?

when I try to type your examples in file rider says only the main file can contain top level statements only

![image](https://github.com/user-attachments/assets/655f5f5a-632d-484e-bff5-754c94cfcc89)

**Comment by wieslawsoltes** [comment]
Its C# issue, please refer to C# documentation about top level statements 

- https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/program-structure/top-level-statements
- https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/top-level-statements
- https://learn.microsoft.com/en-us/dotnet/csharp/tutorials/top-level-statements
